### ISSUE TITLE
Data is not being replace

### ISSUE THREAD

**Issue by jedgar1mx** [CityOfDetroit/property-application#7]
Data is not being overwritten and old answers remain even after submissions.
App ID: EVVWMJ
```
{
propertyUse:
{
commercial-retail:
"commercial-retail",
parking-lot-auto-related:
"parking-lot-auto-related"
}
}
```

**Comment by jedgar1mx** [comment]
If i switch from commercial to parking, the old fields should be removed and replaced.

**Comment by karlkaebnick** [comment]
This is actually intended behavior - "commercial-retail" and "parking-lot-auto-related" are really separate question ids. However, I am adding a separate endpoint so you can delete any existing answers in a section.

**Comment by jedgar1mx** [comment]
created a common field which stores an array of answers as a solution
